controller_joint_names:
  - x_slide_joint
  - y_slide_joint
  - lift_joint
  - torso_pitch_joint
  - neck_joint_1
  - neck_joint_2
  - left_arm_joint_1
  - left_arm_joint_2
  - left_arm_joint_3
  - left_arm_joint_4
  - left_arm_joint_5
  - left_arm_joint_6
  - left_arm_joint_7
  - left_gripper_joint_1
  - left_gripper_joint_2
  - left_gripper_joint_3
  - left_gripper_joint_4
  - left_gripper_joint_5
  - left_gripper_joint_6
  - right_arm_joint_1
  - right_arm_joint_2
  - right_arm_joint_3
  - right_arm_joint_4
  - right_arm_joint_5
  - right_arm_joint_6
  - right_arm_joint_7
  - right_gripper_joint_1
  - right_gripper_joint_2
  - right_gripper_joint_3
  - right_gripper_joint_4
  - right_gripper_joint_5
  - right_gripper_joint_6
